# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171226_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor_competition',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher', to_field='teacher_id'),
        ),
        migrations.AlterField(
            model_name='honor_experience',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher', to_field='teacher_id'),
        ),
        migrations.AlterField(
            model_name='honor_paper_magazine',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher', to_field='teacher_id'),
        ),
        migrations.AlterField(
            model_name='honor_paper_meeting',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher', to_field='teacher_id'),
        ),
        migrations.AlterField(
            model_name='honor_patent',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher', to_field='teacher_id'),
        ),
        migrations.AlterField(
            model_name='honor_scholarship',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher', to_field='teacher_id'),
        ),
    ]
